spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-patient-mud-a15zq0eo-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_i9ZwrkVzxe2R
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
server.address=0.0.0.0
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


# ps -ef | grep java
# sudo ss -tulnp | grep 8080
# tail -f app.log
# java -jar demo-0.0.1-SNAPSHOT.jar
# ssh -i ssh-key-2026-02-28.key opc@140.245.204.216
# scp -i ~/Downloads/ssh-key-2026-02-28.key ~/Documents/Java_Applications/demo/target/demo-0.0.1-SNAPSHOT.jar opc@140.245.204.216:~